title = "Petani Kode"
baseurl = "https://www.petanikode.com/"

# Agar front-matter pakai format YAML
MetaDataFormat = "yaml"

# untuk apply temanya
themesDir = "themes"
theme = "rinzz"

# Shortname disqus, silahkan sesuaikan
DisqusShortname = "petanikode"

# Untuk Google Analytic, silahkan sesuikan
googleAnalytics = "UA-80517197-1" 

# Untuk deskripsi tag meta di homepage
description = "Situs Saya"

# Biodata Author
[author]
    name = "Haikel"
    homepage = "https://github.com/haikelz"
    bio = "Fastabiqul Khoirot"
    image = "https://lh5.googleusercontent.com/-h2tLsyijw8Q/AAAAAAAAAAI/AAAAAAAACys/WBpjN_34z3o/s32-c/photo.jpg"
